name: Create Archive
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'docs.zip'
        exclusions: '*.git* .bumpversion.cfg Makefile mkdocs.yml'
        path: site
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "docs.zip"
        token: ${{ secrets.GITHUB_TOKEN }}